application: myapp
version: gae-client-certificate-testing-2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.application
  secure: always

libraries:
- name: ssl
  version: "latest"